baseurl = "/"
languageCode = "en-us"
title = "onkar singh website"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""

# ignore certain files as recommended
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
    
[[menu.main]]
    name = "Resume"
    url = "/Resume_Onkar_Singh.pdf/"
    weight = 2

[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/onkarsinghcsranddevelopment/"
    weight = 3
    
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/onkartweets"
    weight = 4



[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "Home-Onkar Singh.png"
    width = 50
    height = 50
    alt = "Logo"

